"""Application-owned run-gateway building blocks."""

from .domain import (
    LEGAL_TRANSITIONS,
    TERMINAL_STATES,
    FunctionCallIdentity,
    PollOutcome,
    PollReason,
    PollState,
    Principal,
    Reservation,
    ResolvedDesktop,
    ResolvedTask,
    RunRecord,
    RunState,
    StateTransitionError,
    TrajectoryOutcome,
    TrajectoryStatus,
)
from .http import (
    AuthenticationRequired,
    CancelRunResponse,
    CreateRunRequest,
    GatewayError,
    IdempotencyConflict,
    ObjectNotFound,
    RunConflict,
    RunResponse,
    build_run_gateway_app,
)
from .modal_adapter import ModalTrajectoryDispatcher, build_modal_app
from .ports import PrincipalResolver, RunStore, SessionCatalog, TaskCatalog, TrajectoryDispatcher
from .service import RunGatewayService, admission_fingerprint, utc_now

__all__ = [
    "LEGAL_TRANSITIONS",
    "TERMINAL_STATES",
    "AuthenticationRequired",
    "CancelRunResponse",
    "CreateRunRequest",
    "FunctionCallIdentity",
    "GatewayError",
    "IdempotencyConflict",
    "ModalTrajectoryDispatcher",
    "ObjectNotFound",
    "PollOutcome",
    "PollReason",
    "PollState",
    "Principal",
    "PrincipalResolver",
    "Reservation",
    "ResolvedDesktop",
    "ResolvedTask",
    "RunConflict",
    "RunGatewayService",
    "RunRecord",
    "RunResponse",
    "RunState",
    "RunStore",
    "SessionCatalog",
    "StateTransitionError",
    "TaskCatalog",
    "TrajectoryDispatcher",
    "TrajectoryOutcome",
    "TrajectoryStatus",
    "admission_fingerprint",
    "build_modal_app",
    "build_run_gateway_app",
    "utc_now",
]
