#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.12"
# dependencies = ["markdown-it-py==4.2.0"]
# ///

from __future__ import annotations

import html
import re
from pathlib import Path

from markdown_it import MarkdownIt

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "docs/drafts/modal-optimized-low-latency.md"
OUTPUT = SOURCE.with_suffix(".html")


def render() -> None:
    markdown = SOURCE.read_text(encoding="utf-8")
    title_match = re.search(r"^#\s+(.+)$", markdown, flags=re.MULTILINE)
    title = title_match.group(1) if title_match else SOURCE.stem.replace("-", " ").title()

    renderer = MarkdownIt("commonmark", {"html": False}).enable("table")
    article = renderer.render(markdown)
    article = re.sub(
        r"<table>(.*?)</table>",
        r'<div class="table-scroll"><table>\1</table></div>',
        article,
        flags=re.DOTALL,
    )

    document = f"""<!doctype html>
<!-- Generated by scripts/render_blog_preview.py. -->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="color-scheme" content="light">
  <title>{html.escape(title)}</title>
  <style>
    :root {{
      --ink: #111;
      --muted: #555;
      --rule: #d8d8d8;
      --code-bg: #f5f5f5;
    }}

    * {{ box-sizing: border-box; }}

    html {{ font-size: 18px; }}

    body {{
      margin: 0;
      background: #fff;
      color: var(--ink);
      font-family: Georgia, "Times New Roman", Times, serif;
      line-height: 1.58;
      text-rendering: optimizeLegibility;
    }}

    main {{
      width: min(100% - 2.5rem, 43rem);
      margin: 0 auto;
      padding: 3.5rem 0 6rem;
    }}

    h1, h2, h3 {{
      line-height: 1.18;
      text-wrap: balance;
    }}

    h1 {{
      margin: 0 0 0.8rem;
      font-size: clamp(2rem, 5vw, 2.65rem);
      letter-spacing: -0.025em;
    }}

    h2 {{
      margin: 2.8rem 0 0.8rem;
      font-size: 1.45rem;
      letter-spacing: -0.012em;
    }}

    h3 {{
      margin: 2rem 0 0.65rem;
      font-size: 1.15rem;
    }}

    p {{
      margin: 0.9rem 0;
      text-wrap: pretty;
    }}

    h1 + p {{
      margin: 0 0 2.2rem;
      color: var(--muted);
      font-size: 1.05rem;
      line-height: 1.45;
    }}

    a {{ color: #0000ee; }}
    a:visited {{ color: #551a8b; }}

    img {{
      display: block;
      width: 100%;
      height: auto;
      margin: 2rem auto;
    }}

    code {{
      padding: 0.08em 0.28em;
      background: var(--code-bg);
      font: 0.86em ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
    }}

    pre {{
      overflow-x: auto;
      padding: 1rem;
      background: var(--code-bg);
      line-height: 1.45;
    }}

    pre code {{ padding: 0; }}

    .table-scroll {{
      max-width: 100%;
      margin: 1.5rem 0;
      overflow-x: auto;
      border-top: 1px solid var(--rule);
      border-bottom: 1px solid var(--rule);
    }}

    table {{
      width: max-content;
      min-width: 100%;
      border-collapse: collapse;
      font-size: 0.76rem;
      line-height: 1.35;
      white-space: nowrap;
    }}

    th, td {{
      padding: 0.65rem 0.75rem;
      border-bottom: 1px solid var(--rule);
      text-align: right;
      vertical-align: top;
    }}

    th:first-child, td:first-child {{
      position: sticky;
      left: 0;
      background: #fff;
      text-align: left;
      white-space: normal;
    }}

    tr:last-child td {{ border-bottom: 0; }}

    ul {{ padding-left: 1.25rem; }}
    li {{ margin: 0.4rem 0; }}

    @media (max-width: 600px) {{
      html {{ font-size: 17px; }}
      main {{ width: min(100% - 1.5rem, 43rem); padding-top: 2rem; }}
    }}

    @media print {{
      main {{ width: auto; max-width: none; padding: 0; }}
      a, a:visited {{ color: var(--ink); }}
      img {{ break-inside: avoid; }}
    }}
  </style>
</head>
<body>
  <main>
    {article}
  </main>
</body>
</html>
"""

    OUTPUT.write_text(document, encoding="utf-8")
    print(OUTPUT)


if __name__ == "__main__":
    render()
